CANTON_POPULATION = dict(zip(
    'ZH BE LU UR SZ OW NW GL ZG FR SO BS BL SH AR AI SG GR AG TG TI VD VS NE GE JU'.split(),
    [
        1520968,
        1034977,
        409557,
        36433,
        159165,
        37841,
        43223,
        40403,
        126837,
        318714,
        273194,
        200298,
        289527,
        81991,
        55234,
        16145,
        507697,
        198379 ,
        678207,
        276472,
        353343,
        799145,
        343955,
        176850,
        499480,
        73419,
    ]))

CODE_TO_NAME = {
    'ZH':'Zürich',
    'BE':'Bern',
    'LU':'Luzern',
    'UR':'Uri',
    'SZ':'Schwyz',
    'OW':'Obwalden',
    'NW':'Nidwalden',
    'GL':'Glarus',
    'ZG':'Zug',
    'FR':'Fribourg',
    'SO':'Solothurn',
    'BS':'Basel-Stadt',
    'BL':'Basel-Landschaft',
    'SH':'Schaffhausen',
    'AR':'Appenzell Ausserrhoden',
    'AI':'Appenzell Innerrhoden',
    'SG':'St. Gallen',
    'GR':'Graubünden',
    'AG':'Aargau',
    'TG':'Thurgau',
    'TI':'Ticino',
    'VD':'Vaud',
    'VS':'Valais',
    'NE':'Neuchâtel',
    'GE':'Genève',
    'JU':'Jura',
}

CANTON_LIST = [
                'ZH',
                'BE',
                'LU',
                'UR',
                'SZ',
                'OW',
                'NW',
                'GL',
                'ZG',
                'FR',
                'SO',
                'BS',
                'BL',
                'SH',
                'AR',
                'AI',
                'SG',
                'GR',
                'AG',
                'TG',
                'TI',
                'VD',
                'VS',
                'NE',
                'GE',
                'JU',
                ]

CANTON_LIST_SHORT = [
                'ZH',
                'BE',
                'LU',
                'FR',
                'BS',
                'BL',
                'TI',
                'VD',
                'VS',
                'NE',
                'GE',
                'GR',
                ]
